##
##  Makefile -- Build procedure for sample sqli Apache module
##  Autogenerated via ``apxs -n sqli -g''.
##

builddir=.
top_srcdir=/usr/share/apache2
top_builddir=/usr/share/apache2
include /usr/share/apache2/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
INCLUDES=-I ./include 
LIBS=-L ./include

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_sqli.o mod_sqli.lo mod_sqli.slo mod_sqli.la 

#   simple test
test: reload
	lynx -mime_header "http://localhost:90/sqli?a=-1' union select 1,database(),3,version()--"
	lynx -mime_header "http://localhost:90/sqli?a='><ScRipt>alert(document.domain)</ScRipt>"

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

