/* 
**  mod_sqli.c -- Apache sample sqli module
**  [Autogenerated via ``apxs -n sqli -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_sqli.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /sqli in as follows:
**
**    #   apache2.conf
**    LoadModule sqli_module modules/mod_sqli.so
**    <Location /sqli>
**    SetHandler sqli
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /sqli and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/sqli 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_sqli.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"
#include "include/libinjection.h"

/* The sample content handler */
static int sqli_handler(request_rec *r) {
    int issqli = NULL;
    int isxss = NULL; 
    size_t param = strlen(r->args);

    if (strcmp(r->handler, "sqli")) {
        return DECLINED;
    }

    if (!strcmp(r->method, "POST")) 
        ap_rprintf(r, "POST'ed data: %s\n", r->args);

    if (!strcmp(r->method, "GET")) 
        ap_rprintf(r, "GET'ed data: %s\n", r->args);

    if (r->args) {
        ap_rprintf(r, "Query string: %s\n", r->args);
        issqli = libinjection_sqli(r->args, param, NULL);

        if (issqli) {
            ap_rprintf(r, "SQL Injection detected\n");
        }

        isxss = libinjection_xss(r->args, param);
        if (isxss) 
            ap_rprintf(r, "XSS Injection detected\n");
    }
    return OK;
}

static void sqli_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(sqli_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA sqli_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    sqli_register_hooks  /* register hooks                      */
};

